version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_INTERNAL_PORT}
    volumes:
      - ./docker_volumes/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DB: ${MONGO_DATABASE}
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

#volumes:
#  mongo-data:
#    driver: local
#  mysql-data:
#    driver: local
